

#ifndef __T_CONFIG_H
#define __T_CONFIG_H

#define TINY_OS_PRO_COUNT		32

#define TINY_OS_SLICE_MAX		10

#define TINY_OS_STACK_SIZE		1024

#define TINY_OS_STIMERTASK_STACK_SIZE	1024

#define TINY_OS_STIMER_TASK_PRIO		1

#define TINY_OS_SYSTEM_TICK_MS			10

#endif
